import type { Fighter, Event, NewsArticle } from '@/types';

export const fighters: Fighter[] = [
  {
    id: 'aisha-okonkwo',
    name: 'Aisha Okonkwo',
    nickname: 'The Storm',
    image: '/images/i2.jpg',
    nationality: 'Nigeria',
    flag: '🇳🇬',
    gym: 'Lagos Elite Boxing Club',
    weightClass: 'Lightweight',
    wins: 18,
    losses: 1,
    draws: 0,
    kos: 12,
    rank: 1,
    rankChange: 2,
    xp: 9400,
    level: 94,
    tier: 'Elite',
    stance: 'Orthodox',
    reach: '68"',
    height: "5'7\"",
    age: 26,
    debut: '2019',
    isActive: true,
    points: 1850,
    bio: 'Rising out of Lagos with a record that speaks for itself, Aisha "The Storm" Okonkwo is the most feared lightweight on the planet right now. Her combination speed and knockout power have earned her 12 stoppages from 19 fights.',
    achievements: [
      { id: 'a1', title: 'Unbeaten Streak', description: 'Won 15 consecutive fights', icon: 'Flame', earnedAt: '2024-01' },
      { id: 'a2', title: 'KO Artist', description: 'Finished 10+ opponents by KO/TKO', icon: 'Zap', earnedAt: '2023-08' },
      { id: 'a3', title: 'Rising Star', description: 'Broke into Top 5 rankings', icon: 'Star', earnedAt: '2023-02' },
      { id: 'a4', title: 'Centurion', description: 'Reached Level 90+', icon: 'Shield', earnedAt: '2024-03' },
    ],
    fightHistory: [
      { id: 'f1', date: '2025-11-15', opponent: 'Camila Reyes', opponentRecord: '14-3', result: 'W', method: 'KO', rounds: '5/10', location: 'Lagos, Nigeria', event: 'FemmeBiz Showdown VII' },
      { id: 'f2', date: '2025-07-20', opponent: 'Yuki Tanaka', opponentRecord: '16-2', result: 'W', method: 'UD', rounds: '10/10', location: 'Tokyo, Japan', event: 'Pacific Rim Championships' },
      { id: 'f3', date: '2025-03-08', opponent: 'Sofia Petrov', opponentRecord: '11-1', result: 'W', method: 'TKO', rounds: '7/10', location: 'London, UK', event: "Women's World Boxing Gala" },
      { id: 'f4', date: '2024-10-19', opponent: 'Maria Santos', opponentRecord: '13-0', result: 'L', method: 'SD', rounds: '10/10', location: 'São Paulo, Brazil', event: 'Copa América Boxing' },
      { id: 'f5', date: '2024-05-11', opponent: 'Blessing Adeyemi', opponentRecord: '9-2', result: 'W', method: 'KO', rounds: '3/10', location: 'Abuja, Nigeria', event: 'Nigeria Boxing Invitational' },
    ],
  },
  {
    id: 'diana-chen',
    name: 'Diana Chen',
    nickname: 'Iron Lotus',
    image: '/images/i6.jpg',
    nationality: 'China',
    flag: '🇨🇳',
    gym: 'Shanghai Combat Academy',
    weightClass: 'Flyweight',
    wins: 22,
    losses: 2,
    draws: 1,
    kos: 8,
    rank: 2,
    rankChange: 0,
    xp: 9200,
    level: 92,
    tier: 'Elite',
    stance: 'Southpaw',
    reach: '65"',
    height: "5'4\"",
    age: 28,
    debut: '2017',
    isActive: true,
    points: 1780,
    bio: 'Diana Chen is a technical masterclass in every bout. With 25 fights and a technical repertoire that coaches worldwide study, the "Iron Lotus" is redefining elite female flyweight boxing.',
    achievements: [
      { id: 'a1', title: '20+ Fights', description: 'Accumulated 20 professional bouts', icon: 'Target', earnedAt: '2023-06' },
      { id: 'a2', title: 'Veteran', description: 'Active professional for 5+ years', icon: 'Clock', earnedAt: '2022-01' },
      { id: 'a3', title: 'First Win', description: 'Recorded first professional victory', icon: 'Trophy', earnedAt: '2017-04' },
    ],
    fightHistory: [
      { id: 'f1', date: '2025-09-28', opponent: 'Hana Mori', opponentRecord: '18-1', result: 'W', method: 'MD', rounds: '10/10', location: 'Beijing, China', event: 'Asian Boxing Championships' },
      { id: 'f2', date: '2025-04-14', opponent: 'Leila Ahmadi', opponentRecord: '12-2', result: 'W', method: 'UD', rounds: '10/10', location: 'Dubai, UAE', event: 'Desert Storm Invitational' },
      { id: 'f3', date: '2024-12-07', opponent: 'Rosa Garza', opponentRecord: '15-3', result: 'D', method: 'MD', rounds: '10/10', location: 'Mexico City, MX', event: 'WBC Female Invitational' },
    ],
  },
  {
    id: 'priya-kapoor',
    name: 'Priya Kapoor',
    nickname: 'The Phantom',
    image: '/images/i4.jpg',
    nationality: 'India',
    flag: '🇮🇳',
    gym: 'Mumbai Warriors Gym',
    weightClass: 'Super Featherweight',
    wins: 14,
    losses: 3,
    draws: 1,
    kos: 7,
    rank: 3,
    rankChange: 1,
    xp: 7800,
    level: 78,
    tier: 'Gold',
    stance: 'Orthodox',
    reach: '66"',
    height: "5'5\"",
    age: 23,
    debut: '2021',
    isActive: true,
    points: 1520,
    bio: 'At just 23, Priya Kapoor is the next generation of women\'s boxing. Her elusive footwork and sharp counter-punching have earned her the nickname "The Phantom" — impossible to hit, devastating to catch.',
    achievements: [
      { id: 'a1', title: 'Rising Star', description: 'Broke into Top 5 rankings', icon: 'Star', earnedAt: '2024-07' },
      { id: 'a2', title: 'KO Artist', description: 'Finished 7+ opponents by KO/TKO', icon: 'Zap', earnedAt: '2024-11' },
    ],
    fightHistory: [
      { id: 'f1', date: '2025-10-05', opponent: 'Yara Nassar', opponentRecord: '10-1', result: 'W', method: 'TKO', rounds: '6/10', location: 'New Delhi, India', event: 'South Asian Boxing Cup' },
      { id: 'f2', date: '2025-06-21', opponent: 'Lena Hoffman', opponentRecord: '11-2', result: 'W', method: 'UD', rounds: '10/10', location: 'Berlin, Germany', event: 'European Female Boxing Series' },
    ],
  },
  {
    id: 'valentina-russo',
    name: 'Valentina Russo',
    nickname: 'La Guerriera',
    image: '/images/i1.jpg',
    nationality: 'Italy',
    flag: '🇮🇹',
    gym: 'Palestra Campioni Roma',
    weightClass: 'Welterweight',
    wins: 16,
    losses: 4,
    draws: 0,
    kos: 9,
    rank: 4,
    rankChange: -1,
    xp: 7200,
    level: 72,
    tier: 'Gold',
    stance: 'Orthodox',
    reach: '67"',
    height: "5'6\"",
    age: 27,
    debut: '2018',
    isActive: true,
    points: 1410,
    bio: 'Valentina Russo brings Italian flair and brutal power to the welterweight division. A decorated amateur before turning pro, "La Guerriera" has proven she belongs among the elite.',
    achievements: [
      { id: 'a1', title: 'Veteran', description: 'Active professional for 5+ years', icon: 'Clock', earnedAt: '2023-01' },
      { id: 'a2', title: '10+ Fights', description: 'Completed 10+ professional bouts', icon: 'Target', earnedAt: '2022-03' },
    ],
    fightHistory: [
      { id: 'f1', date: '2025-08-30', opponent: 'Ana Torres', opponentRecord: '13-1', result: 'W', method: 'KO', rounds: '8/10', location: 'Rome, Italy', event: 'FemmeBiz European Grand Prix' },
      { id: 'f2', date: '2025-04-19', opponent: 'Claire Dupont', opponentRecord: '10-2', result: 'L', method: 'UD', rounds: '10/10', location: 'Paris, France', event: 'French Boxing Open' },
    ],
  },
  {
    id: 'zara-osei',
    name: 'Zara Osei',
    nickname: 'The Queen Bee',
    image: '/images/i5.jpg',
    nationality: 'Ghana',
    flag: '🇬🇭',
    gym: 'Accra Boxing Institute',
    weightClass: 'Bantamweight',
    wins: 11,
    losses: 0,
    draws: 0,
    kos: 6,
    rank: 5,
    rankChange: 3,
    xp: 6800,
    level: 68,
    tier: 'Silver',
    stance: 'Southpaw',
    reach: '63"',
    height: "5'3\"",
    age: 21,
    debut: '2023',
    isActive: true,
    points: 1340,
    bio: 'The youngest unbeaten fighter on the platform, Zara "The Queen Bee" Osei has stunned the boxing world with 11 wins from 11 fights, 6 by stoppage. Ghana\'s next world champion is coming.',
    achievements: [
      { id: 'a1', title: 'Unbeaten Streak', description: 'Won 10+ consecutive fights', icon: 'Flame', earnedAt: '2025-04' },
      { id: 'a2', title: 'Rising Star', description: 'Broke into Top 10 rankings', icon: 'Star', earnedAt: '2024-12' },
      { id: 'a3', title: 'First Win', description: 'Recorded first professional victory', icon: 'Trophy', earnedAt: '2023-03' },
    ],
    fightHistory: [
      { id: 'f1', date: '2025-12-01', opponent: 'Fatima Al-Hassan', opponentRecord: '9-2', result: 'W', method: 'TKO', rounds: '4/10', location: 'Accra, Ghana', event: 'West Africa Boxing Night' },
      { id: 'f2', date: '2025-09-14', opponent: 'Abena Mensah', opponentRecord: '7-1', result: 'W', method: 'KO', rounds: '2/10', location: 'Kumasi, Ghana', event: 'Ghana National Championship' },
    ],
  },
  {
    id: 'sofia-herrera',
    name: 'Sofia Herrera',
    nickname: 'La Tigresa',
    image: '/images/i3.jpg',
    nationality: 'Mexico',
    flag: '🇲🇽',
    gym: 'CDMX Elite Fight Team',
    weightClass: 'Super Bantamweight',
    wins: 19,
    losses: 5,
    draws: 2,
    kos: 10,
    rank: 6,
    rankChange: 0,
    xp: 7600,
    level: 76,
    tier: 'Gold',
    stance: 'Orthodox',
    reach: '64"',
    height: "5'4\"",
    age: 30,
    debut: '2016',
    isActive: true,
    points: 1380,
    bio: 'A decade in the ring has made Sofia Herrera one of the most battle-tested fighters on the roster. "La Tigresa" brings explosive aggression and an iron chin that has frustrated even the best.',
    achievements: [
      { id: 'a1', title: '20+ Fights', description: 'Accumulated 20 professional bouts', icon: 'Target', earnedAt: '2024-08' },
      { id: 'a2', title: 'KO Artist', description: 'Finished 10+ opponents by KO/TKO', icon: 'Zap', earnedAt: '2023-09' },
      { id: 'a3', title: 'Veteran', description: 'Active professional for 7+ years', icon: 'Clock', earnedAt: '2023-01' },
    ],
    fightHistory: [
      { id: 'f1', date: '2025-11-08', opponent: 'Keiko Yamamoto', opponentRecord: '14-2', result: 'W', method: 'KO', rounds: '9/10', location: 'Mexico City, MX', event: 'Copa Mexico Boxing' },
      { id: 'f2', date: '2025-07-05', opponent: 'Bianca Costa', opponentRecord: '12-3', result: 'W', method: 'TKO', rounds: '7/10', location: 'Guadalajara, MX', event: 'Jalisco Fight Night' },
    ],
  },
];

export const events: Event[] = [
  {
    id: 'ev-001',
    title: 'FemmeBiz Championship Night XI',
    date: '2026-01-18',
    location: 'London, United Kingdom',
    venue: 'The O2 Arena',
    country: 'UK',
    status: 'upcoming',
    mainEvent: 'Aisha Okonkwo vs. Diana Chen — Lightweight Unification',
    bouts: 8,
  },
  {
    id: 'ev-002',
    title: 'Pacific Rim Female Boxing Summit',
    date: '2026-02-14',
    location: 'Tokyo, Japan',
    venue: 'Ariake Arena',
    country: 'Japan',
    status: 'upcoming',
    mainEvent: 'Yuki Tanaka vs. Priya Kapoor — Super Featherweight',
    bouts: 6,
  },
  {
    id: 'ev-003',
    title: 'West Africa Boxing Night VII',
    date: '2026-03-07',
    location: 'Accra, Ghana',
    venue: 'Accra Sports Stadium',
    country: 'Ghana',
    status: 'upcoming',
    mainEvent: 'Zara Osei vs. TBD — Bantamweight Championship',
    bouts: 7,
  },
  {
    id: 'ev-004',
    title: 'FemmeBiz European Grand Prix',
    date: '2025-08-30',
    location: 'Rome, Italy',
    venue: 'Palazzetto dello Sport',
    country: 'Italy',
    status: 'completed',
    mainEvent: 'Valentina Russo vs. Ana Torres',
    bouts: 9,
  },
  {
    id: 'ev-005',
    title: 'Copa América Women\'s Boxing',
    date: '2025-10-12',
    location: 'Buenos Aires, Argentina',
    venue: 'Luna Park',
    country: 'Argentina',
    status: 'completed',
    mainEvent: 'Sofia Herrera vs. Keiko Yamamoto',
    bouts: 6,
  },
  {
    id: 'ev-006',
    title: 'FemmeBiz Showdown VII',
    date: '2025-11-15',
    location: 'Lagos, Nigeria',
    venue: 'Teslim Balogun Stadium',
    country: 'Nigeria',
    status: 'completed',
    mainEvent: 'Aisha Okonkwo vs. Camila Reyes',
    bouts: 8,
  },
];

export const news: NewsArticle[] = [
  {
    id: 'n-001',
    title: 'Aisha Okonkwo Calls Out Diana Chen for Unification Bout',
    excerpt: 'The lightweight world is buzzing after Okonkwo\'s post-fight interview where she pointed directly at the Iron Lotus: "She\'s the only one I want."',
    category: 'Breaking News',
    date: '2025-12-10',
    author: 'Amara Diallo',
    image: '/images/i2.jpg',
    readTime: '3 min',
  },
  {
    id: 'n-002',
    title: 'Zara Osei: Ghana\'s Youngest Unbeaten Sensation Eyes World Title',
    excerpt: 'At 21, Zara Osei is already ranked 5th globally with a perfect 11-0 record. We spoke to the "Queen Bee" about her rise, her ambitions, and life at the top.',
    category: 'Feature',
    date: '2025-12-08',
    author: 'Nkechi Eze',
    image: '/images/i5.jpg',
    readTime: '6 min',
  },
  {
    id: 'n-003',
    title: 'FemmeBiz Championship Night XI Card Announced: Eight Bouts at The O2',
    excerpt: 'The January mega-card is here. Eight fights, four weight classes, and a main event that the entire boxing world is waiting for.',
    category: 'Event News',
    date: '2025-12-05',
    author: 'FemmeBiz Editorial',
    image: '/images/i3.jpg',
    readTime: '4 min',
  },
  {
    id: 'n-004',
    title: 'Training Day: Inside Priya Kapoor\'s Preparation at Mumbai Warriors',
    excerpt: 'We followed "The Phantom" through a full week of training camp ahead of her December clash — the footwork drills that make opponents miss, the diet, the mindset.',
    category: 'Training & Fitness',
    date: '2025-12-01',
    author: 'Riya Mehta',
    image: '/images/i4.jpg',
    readTime: '7 min',
  },
  {
    id: 'n-005',
    title: 'The Science of Women\'s Boxing: Why the Sport Is Growing Faster Than Ever',
    excerpt: 'New data shows a 47% increase in registered female professional boxers globally since 2022. FemmeBiz unpacks the numbers and the stories behind them.',
    category: 'Analysis',
    date: '2025-11-28',
    author: 'Dr. Chioma Adeyemi',
    image: '/images/i1.jpg',
    readTime: '8 min',
  },
  {
    id: 'n-006',
    title: 'Sofia Herrera on a Decade in Boxing: "The Ring Has Given Me Everything"',
    excerpt: 'With 26 professional fights behind her, La Tigresa reflects on the sacrifices, the victories, and what drives her at 30 to keep going.',
    category: 'Interview',
    date: '2025-11-20',
    author: 'Lucia Fernandez',
    image: '/images/i6.jpg',
    readTime: '9 min',
  },
];

export const weightClasses = [
  'Strawweight',
  'Super Strawweight',
  'Light Flyweight',
  'Flyweight',
  'Super Flyweight',
  'Bantamweight',
  'Super Bantamweight',
  'Featherweight',
  'Super Featherweight',
  'Lightweight',
  'Super Lightweight',
  'Welterweight',
  'Super Welterweight',
  'Middleweight',
  'Super Middleweight',
  'Light Heavyweight',
  'Cruiserweight',
  'Heavyweight',
] as const;

export const platformStats = {
  fighters: 12,
  fights: 34,
  gyms: 4,
  countries: 3,
};
